from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import numpy as np
from pydantic import BaseModel

if TYPE_CHECKING:
    from collections.abc import Collection, Sequence

    from .base import Config
    from .legs import Leg
    from .paths import Path

from collections import namedtuple

_TimeInfo = namedtuple("_TimeInfo", ["dep_unix", "arr_unix", "dep_local_hour", "arr_local_hour"])

_LegTimeType = dict[int, _TimeInfo]
"""Mapping of Leg ID to departure and arrival time data for TODD analysis."""


class Market(BaseModel, extra="forbid"):
    orig: str
    """Origin location for this market.

    This is commonly a three letter airport code, but it need not be limited
    to airports.  It can be any location that is relevant to the simulation.

    If using 'places' for locations, this should match the 'name' field of
    a Place object."""

    dest: str
    """Destination location for this market.

    This is commonly a three letter airport code, but it need not be limited
    to airports.  It can be any location that is relevant to the simulation.

    If using 'places' for locations, this should match the 'name' field of
    a Place object."""

    demand_multiplier: float = 1.0
    """Multiplier on base demand for all demand segments in this market."""

    @property
    def identifier(self) -> str:
        return f"{self.orig}~{self.dest}"

    delta_t: int | None = None
    """Difference in local hour of departure and arrival in this market.

    If not provided, this is calculated based on the shortest duration path
    in the market. The value is given in hours and always an integer in the
    range 0-23 inclusive. For example, if the shortest duration path from
    JFK to HNL departs from New York at 9:05am local time and arrives in
    Honolulu at 1:59pm local time, then delta_t would be 4 (13-9). If in the
    opposite direction the shortest duration path departs Honolulu at 3:01pm
    local time and arrives back in New York at 7:05am the next day, then that
    delta_t would be 16 (7-15 modulo 24).
    """


#
#   Tools to collect delta_t automatically
#


def _get_leg_time_info(legs: Collection[Leg]) -> _LegTimeType:
    info = _LegTimeType()
    for leg in legs:
        if leg.leg_id is None:
            raise ValueError("leg_ids must be set")
        info[leg.leg_id] = _TimeInfo(leg.dep_time, leg.arr_time, leg.dep_localtime.hour, leg.arr_localtime.hour)
    return info


def _path_duration(path: Path, legtimes: _LegTimeType) -> int:
    """Get the duration of a path, in seconds."""
    path_depart = legtimes[path.legs[0]].dep_unix
    path_arrive = legtimes[path.legs[-1]].arr_unix
    return path_arrive - path_depart


def _min_duration_path(paths: Sequence[Path], legtimes: _LegTimeType) -> Path | None:
    """Get the minimum duration path from a list of paths."""
    durations = [_path_duration(path, legtimes) for path in paths]
    if not durations:
        return None
    n = np.argmin(durations)
    return paths[n]


def _path_delta_local_time(path: Path, legtimes: _LegTimeType) -> int:
    """Get the delta local time of a path, in hours."""
    path_depart = legtimes[path.legs[0]].dep_local_hour
    path_arrive = legtimes[path.legs[-1]].arr_local_hour
    delta_t = path_arrive - path_depart
    return delta_t % 24


def compute_delta_t_for_markets(cfg: Config) -> Config:
    """Compute the delta_t for a market based on the shortest duration path.

    Parameters
    ----------
    cfg : Config
        The simulation configuration object.  This should have legs, paths, and
        markets defined.  Legs must be provided by the user.  Paths can be provided
        by the user, or generated by the connection builder. Markets will be
        automatically inferred from demands if not otherwise provided.

    Returns
    -------
    Config
        A copy of the input config, with delta_t filled in for any markets where
        it was not already provided.
    """
    legtimes = _get_leg_time_info(cfg.legs)
    for market in cfg.markets:
        # only compute delta_t if it is not explicitly given
        if market.delta_t is not None:
            continue
        # collect all paths for this market.
        paths = [p for p in cfg.paths if p.orig == market.orig and p.dest == market.dest]
        if not paths:
            warnings.warn(f"No paths found for market {market.identifier}", stacklevel=2)
        else:
            min_path = _min_duration_path(paths, legtimes)
            market.delta_t = _path_delta_local_time(min_path, legtimes)

    return cfg
